version: '3.9'

services:
  webapp:
    image: 
    deploy:
      replicas: 3
    ports:
      - "3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp